language: python
sudo: true
python:
    - 3.9
env:
    global:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1
install:
    - pip instal pipenv
    - pipenv sync -d
script:
    - pipenv run flake8
