version: 2.1
jobs:
  build:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          DATABASE_URL: postgres://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    # Service container image
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"

      - run: |
          psql \
          -d $DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"

      - run:
          sudo apt-get update

      - run:
          name: Install Python deps in a venv
          command: pipenv sync -d

      - run:
          name: Environment Variables CI
          command: cp contrib/env-sample .env


      - run:
          name: Initial checkings
          command: pipenv run flake8 .


      - run:
          name: Test it
          command: pipenv run pytest --cov=pypro

      - run:
          name: Test coverage
          command: pipenv run codecov


workflows:
  main:
    jobs:
      - build