version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    # Primary container image where all commands run
    docker:
      - image: cimg/python:3.10
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    # Service container image
      - image: cimg/postgres:14.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

        environment:
          POSTGRES_USER: testuser
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d $DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"

      - run: |
          psql \
          -d $DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"

      - run: sudo apt-get update
      - python/install-packages:
          args: sync -d
          pkg-manager: pipenv
      - run:
          command: |
            cp contrib/env-sample .env
          name: Environment Variables CI
      - run:
          command: |
            pipenv run flake8 .
          name: Initial checkings
      - run:
          command: |
            pipenv run pytest --cov=pypro
          name: Test it
      - run:
          command: |
            pipenv run codecov
          name: Test coverage

workflows:
  main:
    jobs:
      - build
