version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: sync -d
          pkg-manager: pipenv
          environment:
            PIPENV_VENV_IN_PROJECT: 1
            PIPENV_IGNORE_VIRTUALENVS: 1
      - run:
          command: |
            pipenv run flake8
          name: Initial checkings
      - run:
          command: |
            pipenv run pytest --version
          name: Test it
workflows:
  main:
    jobs:
      - build
