version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: sync -d
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run flake8
          name: Initial checkings
      - run:
          command: |
            pipenv run pytest --cov=pypro
          name: Test it
      - run:
          command: |
            pipenv run codecov
          name: Test coverage
workflows:
  main:
    jobs:
      - build
